spring.datasource.url=jdbc:mysql://localhost:3306/sentinel_db
spring.datasource.username=root
spring.datasource.password=Mohit@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
spring.application.name=SENTINEL
jwt.secret=SentinelSuperSecretKey2026SIHProjectMinistryOfHomeAffairs
jwt.expiration=900000
jwt.refresh-expiration=604800000
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
